import { Team, Match, Player, AnnouncementSlide, HighlightItem } from './types';

export const VENUES = [
  'Beaulieu Stadium',
  'Club 1 Stadium',
  'Harrach Stadium'
] as const;

export const TEAMS: Team[] = [
  {
    id: 'team-auto',
    code: 'AUTO',
    name: 'AUTO',
    department: 'Automation Engineering',
    badgeUrl: '/assets/AUTO.png',
    captainName: 'Bennouar Mohamed Amine',
  },
  {
    id: 'team-data',
    code: 'DATA',
    name: 'DATA',
    department: 'Data Science & A.I. Engineering',
    badgeUrl: '/assets/DATA.png',
    captainName: 'Aouanouk Ahcene Zakaria',
  },
  {
    id: 'team-eln',
    code: 'ELN',
    name: 'ELN',
    department: 'Electronics',
    badgeUrl: '/assets/ELN.png',
    captainName: 'Bedka Mohamed',
  },
  {
    id: 'team-elt',
    code: 'ELT',
    name: 'ELT',
    department: 'Electrical',
    badgeUrl: '/assets/ELT.png',
    captainName: 'Louni Iskandar Yanir',
  },
  {
    id: 'team-indus',
    code: 'INDUS',
    name: 'INDUS',
    department: 'Industrial',
    badgeUrl: '/assets/INDUS.png',
    captainName: 'Himeur Yahia Anis',
  },
  {
    id: 'team-meca',
    code: 'MECA',
    name: 'MECA',
    department: 'Mechanical Engineering',
    badgeUrl: '/assets/MECA.png',
    captainName: 'Bakrar Lazher Amir El Islam',
  },
  {
    id: 'team-mtrx',
    code: 'MTRX',
    name: 'MTRX',
    department: 'Materials (Matériaux)',
    badgeUrl: '/assets/mtrx.png',
    captainName: 'Taieb Islem Bouzaghou',
  },
  {
    id: 'team-qhse',
    code: 'QHSE',
    name: 'QHSE',
    department: 'QHSE',
    badgeUrl: '/assets/QHSE.png',
    captainName: 'Mohamed Djihad Taieb Errahmani',
  },
];

// Squads are NOT yet selected; they will be registered autonomously by each captain through the Captain Portal.
export const INITIAL_PLAYERS: Player[] = [];

export const INITIAL_MATCHES: Match[] = [];
/*
export const SEEDED_MATCHES: Match[] = [
  // --- MATCHDAY 1 (Matches recorded from Desgin_System.ai source of truth) ---
  {
    id: 'm-md1-1',
    phase: 'league',
    matchday: 1,
    roundLabel: 'Matchday 1',
    homeTeamId: 'team-eln',
    awayTeamId: 'team-elt',
    homeTeam: TEAMS[2],
    awayTeam: TEAMS[3],
    scheduledAt: '2026-10-09T10:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: 3,
    awayScore: 3,
    status: 'finished',
    lastUpdatedBy: 'Bedka Mohamed',
  },
  {
    id: 'm-md1-2',
    phase: 'league',
    matchday: 1,
    roundLabel: 'Matchday 1',
    homeTeamId: 'team-indus',
    awayTeamId: 'team-elt',
    homeTeam: TEAMS[4],
    awayTeam: TEAMS[3],
    scheduledAt: '2026-10-09T13:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: 1,
    awayScore: 4,
    status: 'finished',
    lastUpdatedBy: 'Louni Iskandar Yanir',
  },
  {
    id: 'm-md1-3',
    phase: 'league',
    matchday: 1,
    roundLabel: 'Matchday 1',
    homeTeamId: 'team-data',
    awayTeamId: 'team-meca',
    homeTeam: TEAMS[1],
    awayTeam: TEAMS[5],
    scheduledAt: '2026-10-13T14:00:00Z',
    venue: 'Club 1 Stadium',
    homeScore: 3,
    awayScore: 5,
    status: 'finished',
    lastUpdatedBy: 'Bakrar Lazher Amir El Islam',
  },
  {
    id: 'm-md1-4',
    phase: 'league',
    matchday: 1,
    roundLabel: 'Matchday 1',
    homeTeamId: 'team-qhse',
    awayTeamId: 'team-auto',
    homeTeam: TEAMS[7],
    awayTeam: TEAMS[0],
    scheduledAt: '2026-10-13T16:00:00Z',
    venue: 'Harrach Stadium',
    homeScore: 2,
    awayScore: 1,
    status: 'finished',
    lastUpdatedBy: 'Mohamed Djihad Taieb Errahmani',
  },

  // --- MATCHDAY 2 ---
  {
    id: 'm-md2-1',
    phase: 'league',
    matchday: 2,
    roundLabel: 'Matchday 2',
    homeTeamId: 'team-auto',
    awayTeamId: 'team-data',
    homeTeam: TEAMS[0],
    awayTeam: TEAMS[1],
    scheduledAt: '2026-10-16T10:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: 2,
    awayScore: 1,
    status: 'live',
    lastUpdatedBy: 'Bennouar Mohamed Amine',
  },
  {
    id: 'm-md2-2',
    phase: 'league',
    matchday: 2,
    roundLabel: 'Matchday 2',
    homeTeamId: 'team-eln',
    awayTeamId: 'team-mtrx',
    homeTeam: TEAMS[2],
    awayTeam: TEAMS[6],
    scheduledAt: '2026-10-16T13:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md2-3',
    phase: 'league',
    matchday: 2,
    roundLabel: 'Matchday 2',
    homeTeamId: 'team-meca',
    awayTeamId: 'team-indus',
    homeTeam: TEAMS[5],
    awayTeam: TEAMS[4],
    scheduledAt: '2026-10-19T14:00:00Z',
    venue: 'Club 1 Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md2-4',
    phase: 'league',
    matchday: 2,
    roundLabel: 'Matchday 2',
    homeTeamId: 'team-elt',
    awayTeamId: 'team-qhse',
    homeTeam: TEAMS[3],
    awayTeam: TEAMS[7],
    scheduledAt: '2026-10-19T16:00:00Z',
    venue: 'Harrach Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },

  // --- MATCHDAY 3 ---
  {
    id: 'm-md3-1',
    phase: 'league',
    matchday: 3,
    roundLabel: 'Matchday 3',
    homeTeamId: 'team-mtrx',
    awayTeamId: 'team-auto',
    homeTeam: TEAMS[6],
    awayTeam: TEAMS[0],
    scheduledAt: '2026-10-23T10:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md3-2',
    phase: 'league',
    matchday: 3,
    roundLabel: 'Matchday 3',
    homeTeamId: 'team-data',
    awayTeamId: 'team-indus',
    homeTeam: TEAMS[1],
    awayTeam: TEAMS[4],
    scheduledAt: '2026-10-23T13:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md3-3',
    phase: 'league',
    matchday: 3,
    roundLabel: 'Matchday 3',
    homeTeamId: 'team-eln',
    awayTeamId: 'team-qhse',
    homeTeam: TEAMS[2],
    awayTeam: TEAMS[7],
    scheduledAt: '2026-10-26T14:00:00Z',
    venue: 'Club 1 Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md3-4',
    phase: 'league',
    matchday: 3,
    roundLabel: 'Matchday 3',
    homeTeamId: 'team-elt',
    awayTeamId: 'team-meca',
    homeTeam: TEAMS[3],
    awayTeam: TEAMS[5],
    scheduledAt: '2026-10-26T16:00:00Z',
    venue: 'Harrach Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },

  // --- MATCHDAY 4 ---
  {
    id: 'm-md4-1',
    phase: 'league',
    matchday: 4,
    roundLabel: 'Matchday 4',
    homeTeamId: 'team-qhse',
    awayTeamId: 'team-mtrx',
    homeTeam: TEAMS[7],
    awayTeam: TEAMS[6],
    scheduledAt: '2026-10-30T10:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md4-2',
    phase: 'league',
    matchday: 4,
    roundLabel: 'Matchday 4',
    homeTeamId: 'team-meca',
    awayTeamId: 'team-auto',
    homeTeam: TEAMS[5],
    awayTeam: TEAMS[0],
    scheduledAt: '2026-10-30T13:00:00Z',
    venue: 'Beaulieu Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md4-3',
    phase: 'league',
    matchday: 4,
    roundLabel: 'Matchday 4',
    homeTeamId: 'team-indus',
    awayTeamId: 'team-eln',
    homeTeam: TEAMS[4],
    awayTeam: TEAMS[2],
    scheduledAt: '2026-11-02T14:00:00Z',
    venue: 'Club 1 Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
  {
    id: 'm-md4-4',
    phase: 'league',
    matchday: 4,
    roundLabel: 'Matchday 4',
    homeTeamId: 'team-data',
    awayTeamId: 'team-elt',
    homeTeam: TEAMS[1],
    awayTeam: TEAMS[3],
    scheduledAt: '2026-11-02T16:00:00Z',
    venue: 'Harrach Stadium',
    homeScore: null,
    awayScore: null,
    status: 'scheduled',
  },
];
*/

export const ANNOUNCEMENTS: AnnouncementSlide[] = [
  {
    id: 'ann-1',
    tag: 'ANNOUNCEMENT',
    title: 'POLY LEAGUE IS BACK AGAIN',
    subtitle: 'Season 2026 / 2027',
    content: 'Poly League is back again with another season and another format, featuring 8 departments to compete for the championship. The format this season will be divided into 2 phases: the League Phase (UCL style) and the Knockout Final Phase.',
    date: 'Official Release',
  },
  {
    id: 'ann-2',
    tag: 'TOURNAMENT FORMAT',
    title: 'PHASE 1: UCL LEAGUE FORMAT',
    subtitle: '8 Teams, 4 Games Each',
    content: 'Starting with the League Phase, each of the 8 teams will play 4 intense matches with fixtures determined by the official live draw. Standings dictate the fate of each department.',
    date: 'Rules & Format',
  },
  {
    id: 'ann-3',
    tag: 'QUALIFICATION CRITERIA',
    title: 'THE QUALIFYING ZONES',
    subtitle: 'Direct, Play-offs & Relegation',
    content: 'At the end of the League Phase, the top 2 teams in the standings proceed directly to the Final Phase Semi-Finals. Teams 7th and 8th are eliminated. Teams 3rd through 6th battle in high-stakes Play-offs!',
    date: 'Standings Rules',
  },
  {
    id: 'ann-4',
    tag: 'THE FINAL PHASE',
    title: 'PLAY-OFFS & THE GRAND FINAL',
    subtitle: 'Single Knockout Bracket',
    content: 'The 3rd to 6th placed teams clash in single-elimination play-offs to determine the 2 remaining semifinalists, joining the top 2 seeds for the ultimate championship showdown.',
    date: 'Championship Track',
  },
  {
    id: 'ann-5',
    tag: 'TEAM CAPTAINS',
    title: 'THE 8 DEPARTMENT CAPTAINS',
    subtitle: 'Autonomous Match & Squad Leadership',
    content: 'Every department is represented and organized by its official captain. Captains hold direct authority to schedule fixtures, manage rosters, and register live scores in the Poly League portal.',
    date: 'Captains Roster',
  },
];

export const HIGHLIGHTS: HighlightItem[] = [
  {
    id: 'hl-polyback',
    season: '2026 Launch',
    title: 'A New Format. A Bigger Fight.',
    description: 'Poly League returns with a new two-phase format built for more tension, more turning points, and one unforgettable champion.',
    mediaUrl: '/assets/editorial/polyback.jpeg',
    mediaType: 'image',
    tags: ['Return', 'New Format', 'Season 2026'],
  },
  {
    id: 'hl-indus-malik',
    season: '2025 Edition',
    title: 'Hammada Masterclass Seals the Comeback',
    description: 'INDUS turned a thriller against DATA on its head with a late comeback, driven by a decisive Hammada masterclass.',
    mediaUrl: '/assets/editorial/indus-malik.jpg',
    mediaType: 'image',
    tags: ['INDUS', 'Comeback', 'Matchday'],
  },
  {
    id: 'hl-data-zaki',
    season: '2025 Edition',
    title: 'DATA Hold the Line and Break Through',
    description: 'Captain Zaki celebrates with the DATA supporters after defensive heroics carried the department into the knockout phase.',
    mediaUrl: '/assets/editorial/data-zaki.jpeg',
    mediaType: 'image',
    tags: ['DATA', 'Knockouts', 'Defensive Wall'],
  },
  {
    id: 'hl-eln-mouici',
    season: '2025 Edition',
    title: 'Mouici Keeps ELN Hungry',
    description: 'After the 5–2 loss to QHSE, ELN center back Mouici gathered the team, praised its resilience, and pointed toward this season’s fight.',
    mediaUrl: '/assets/editorial/eln-mouici.jpeg',
    mediaType: 'image',
    tags: ['ELN', 'Resilience', 'Captaincy'],
  },
  {
    id: 'hl-1',
    season: '2025 Edition',
    title: 'Grand Final Thriller: MECA vs ELT',
    description: 'An unforgettable 3-2 comeback victory in extra time before 800 screaming students.',
    mediaUrl: '/assets/MECA.png',
    mediaType: 'image',
    tags: ['Finals', 'Champions', 'Trophy'],
  },
  {
    id: 'hl-2',
    season: '2025 Edition',
    title: 'Golden Boot Winner: 9 Goals in 5 Games',
    description: 'A stellar performance throughout the tournament with top-tier finishing from outside the box.',
    mediaUrl: '/assets/ELT.png',
    mediaType: 'image',
    tags: ['Awards', 'Golden Boot'],
  },
  {
    id: 'hl-3',
    season: '2025 Edition',
    title: 'Best Goalkeeper of the Tournament',
    description: 'Three clean sheets in the group phase and two penalty saves that secured a semifinal spot.',
    mediaUrl: '/assets/DATA.png',
    mediaType: 'image',
    tags: ['Golden Glove', 'Defense'],
  },
];
